services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
        #$projectDir: '%kernel.project_dir%'

    Markocupic\RszMaterialinventarBundle\:
        resource: ../src/
        exclude: [ '../src/{DependencyInjection,Model,ContaoManager}']
